version: '2.3'

services:
    galactic:
        build:
            context: ../
            dockerfile: pi-node/Dockerfile
        restart: always
        privileged: true
        devices:
            - /dev/gpiomem
            - /dev/video0

        command: ros2 launch /app/ros2_ws/src/dooby_interface/launch/interface_launch.py
        network_mode: service:husarnet  # This is the most important line in this setup. This will put the Husarnet Client in the same network namespace as your app 

    husarnet:
        image: husarnet/husarnet
        restart: unless-stopped
        volumes:
            - /var/lib/husarnet  # This will persist your Husarnet Client keys, thus IP of the container will be stable/the same between (re)boots
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0  # Husarnet is using IPv6 for the internal connections
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
        environment:
            - HOSTNAME=pi-node
        env_file: 
            - ../.env  # create .env file in the same folder as Dockerfile and specify HOSTNAME and JOINCODE there