version: '3.2'

services:
  # ROS 2 Galactic
  galactic:
    build:
            context: ../
            dockerfile: dev-node/Dockerfile
    restart: unless-stopped
    volumes:
      - ./config.rviz:/root/.rviz2/default.rviz
      - ../ros2_ws/src:/app/ros2_ws/src
      - ./cyclonedds.xml:/cyclonedds.xml # remove this in production
    ports: 
      - 6080:80
    shm_size: '512m'
    command: cd ros2_ws && colcon build


  husarnet:
    image: husarnet/husarnet
    restart: unless-stopped
    volumes:
      - /var/lib/husarnet  # This will persist your Husarnet Client keys, thus IP of the container will be stable/the same between (re)boots
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0  # Husarnet is using IPv6 for the internal connections
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    env_file: 
      - ./.env  # create .env file in the same folder as Dockerfile and specify HOSTNAME and JOINCODE there
    network_mode: service:galactic  # This is the most important line in this setup. This will put the Husarnet Client in the same network namespace as your app 
