version: '2.3'

services:
    galactic:
        build:
            context: ../
            dockerfile: server-node/Dockerfile
        restart: always
        volumes:
            - ./config.rviz:/root/.rviz2/default.rviz
            - ../ros2_ws/src:/app/ros2_ws/src
        command: ros2 launch nav2_bringup bringup_launch.py params_file:=/app/ros2_ws/src/dooby_simulation/config/nav2_params.yaml map:=/app/ros2_ws/src/dooby_simulation/map/map.yaml #package node
        network_mode: service:husarnet  # This is the most important line in this setup. This will put the Husarnet Client in the same network namespace as your app 

    husarnet:
        image: husarnet/husarnet
        restart: unless-stopped
        volumes:
            - /var/lib/husarnet  # This will persist your Husarnet Client keys, thus IP of the container will be stable/the same between (re)boots
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0  # Husarnet is using IPv6 for the internal connections
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
        env_file: 
            - ./.env  # create .env file in the same folder as Dockerfile and specify HOSTNAME and JOINCODE there